# Generated by Django 3.0.2 on 2020-01-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIPlantRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default='', max_length=15)),
                ('synonymSymbol', models.CharField(blank=True, default='', max_length=15)),
                ('scientificNameAuthor', models.CharField(blank=True, default='', max_length=500)),
                ('nationalCommonName', models.CharField(blank=True, default='', max_length=500)),
                ('family', models.CharField(blank=True, default='', max_length=250)),
                ('nativeState', models.CharField(max_length=100)),
                ('isInvasive', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['scientificNameAuthor'],
            },
        ),
    ]
