# Generated by Django 3.0.2 on 2020-01-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiplantrecord',
            name='isInvasive',
            field=models.CharField(max_length=20),
        ),
    ]
